[project]
name = "zuni"
version = "0.1.0"
description = "Small CLI doubt solver."
readme = "README.md"
authors = [
    { name = "ssannssarr", email = "ssantanusarkar8@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
]

[project.scripts]
zuni = "zuni:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
