[project]
name = "ssannssarr.zuni"
version = "0.1.0"
description = "Small CLI doubt solver."
readme = "README.md"
authors = [
    { name = "ssannssarr", email = "ssantanusarkar8@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "asyncclick>=8.4.2.1",
    "bs4>=0.0.2",
    "curl-cffi>=0.16.3",
    "httpx>=0.28.1",
    "rich>=15.0.0",
    "markdownify>=1.0.0",
]

[project.scripts]
zuni = "zuni.cli:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "zuni"

[dependency-groups]
dev = [
    "mkdocs-material>=9.7.7",
]

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
